media:
  input: public
  output: /

content:
  # Documentation collection
  - name: docs
    label: Documentation
    type: collection
    path: src/content/docs
    view:
      fields: [title, category, order, draft]
      sort: [category, order]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: string
        required: true
      - name: category
        label: Category
        type: string
        required: true
        options:
          values:
            - { label: "Getting Started", value: "getting-started" }
            - { label: "Guides", value: "guides" }
            - { label: "Reference/API", value: "reference" }
            - { label: "FAQ", value: "faq" }
      - name: order
        label: Sort Order
        type: number
        default: 999
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: lastUpdated
        label: Last Updated
        type: date
      - name: sidebar
        label: Sidebar Options
        type: object
        fields:
          - name: label
            label: Sidebar Label
            type: string
          - name: icon
            label: Icon
            type: string
          - name: badge
            label: Badge
            type: string
            options:
              values:
                - { label: "None", value: "" }
                - { label: "New", value: "new" }
                - { label: "Beta", value: "beta" }
                - { label: "Deprecated", value: "deprecated" }
      - name: ogImage
        label: OG Image
        type: image
      - name: canonicalURL
        label: Canonical URL
        type: string
      - name: body
        label: Content
        type: rich-text

  # Services/Booking collection
  - name: services
    label: Booking Services
    type: collection
    path: src/content/services
    view:
      fields: [title, price, highlighted, order]
    fields:
      - name: title
        label: Service Title
        type: string
        required: true
      - name: description
        label: Description
        type: string
        required: true
      - name: price
        label: Price
        type: string
        required: true
      - name: duration
        label: Duration
        type: string
      - name: priceType
        label: Price Type
        type: string
        default: hourly
        options:
          values:
            - { label: "Hourly Rate", value: "hourly" }
            - { label: "Flat Rate", value: "flat" }
            - { label: "Custom Quote", value: "custom" }
      - name: features
        label: Features
        type: string
        list: true
      - name: bookingUrl
        label: Booking URL
        type: string
        required: true
      - name: order
        label: Sort Order
        type: number
        default: 999
      - name: highlighted
        label: Featured
        type: boolean
        default: false
      - name: availability
        label: Availability
        type: string
      - name: body
        label: Additional Details
        type: rich-text

  # Keep existing blog posts (optional)
  - name: posts
    label: Blog Posts
    type: collection
    path: src/content/blog
    view:
      fields: [title, draft, pubDatetime]
    fields:
      - { name: author, label: Author, type: string }
      - { name: pubDatetime, label: Publish Date, type: date }
      - { name: modDatetime, label: Modified Date, type: date }
      - { name: title, label: Title, type: string, required: true }
      - { name: ogImage, label: OG Image, type: string }
      - { name: slug, label: Slug, type: string }
      - { name: featured, label: Featured, type: boolean }
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: description, label: Description, type: string }
      - { name: body, label: Body, type: rich-text }

  # About page
  - name: about
    label: About page
    type: file
    path: src/pages/about.md
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/AboutLayout.astro" }
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text, options: { input: public/assets, output: /assets } }
